### PR TITLE
Add placeholder to facilitate customization of forms

### PR DESCRIPTION
**Pull request by MarionCouesnon**

### CODE REVIEW

**Comment by tysongach** [comment]
👍 I’m good with this. I sometimes make the placeholders a bit darker to (somewhat) improve color contrast.

**Comment by whmii** [comment]
Yep, I'm down. good to merge

**Comment by whmii** [comment]
@MarionCouesnon can you rebase this. then I can merge your commit.

**Comment by MarionCouesnon** [comment]
Done :)

**Comment by whmii** [comment]
thanks @MarionCouesnon

**Comment by cappadona** [comment]
Just curious, but from what I can tell, this seems to be the first *and only* occurrence of using one of the [default colors](https://github.com/thoughtbot/bitters/blob/344099534490aa06bd829523f134142e56bbdabd/core/_variables.scss#L22-L26) from `_variables.scss` outside of the file itself.

So if you happen to define your own colors, and they don't include `$medium-gray`, this will result in a compilation error. Perhaps heading in this direction was unavoidable, and if so, please ignore :)

It just caught me off-guard.

Thanks for your time.

**Comment by whmii** [comment]
@cappadona You are correct. This should be adjusted prior to any further release. I will create an issue.

**Comment by cappadona** [comment]
Thanks @whmii!

**Pull request merged**
