### PR TITLE
Added bower.json and package.json

### PR DESCRIPTION
**Pull request by re6exp**
Added bower.json and package.json to make possible to install through bower and npm.

### CODE REVIEW

**Comment by tysongach** [comment]
We don’t publish Bitters to npm or Bower because we expect the code to changed by the end-user. More info [here](https://github.com/thoughtbot/bitters/issues/127).

**Comment by re6exp** [comment]
I'm using my styles with webpack/sass-loader. So I do have no need to install gems to get content of the styles which simply copying by bitter CLI. It is great to them who are using ruby/RoR only. But others are aside.

In case you have described I have no possibility to get basis with default settings like any other libraries/frameworks do and apply my own changes later. Sure, I'm not alone with this situation.

Anyway, thx.

**Comment by tysongach** [comment]
@re6exp Bitters is a scaffold, a “jumping off” point for base styling. It’s meant to be installed at the beginning of your project and be changed/tweaked throughout the lifetime of a project. It should live within the same directory as your other project-specific styles and is not expected to be updated/reinstalled again.

**Comment by tysongach** [comment]
The Bitters gem/CLI is not for _installing_ in a Rails project through the Gemfile, but rather a tool to quickly place all of Bitters’ Sass partials in your project.

**Comment by re6exp** [comment]
Ok, I got it. Thank you for your clarification.

**Pull request closed without merging**
