### PR TITLE
Accommodate nested default placeholder ol and ul styles

### PR DESCRIPTION
**Pull request by kristianserrano**
Adds ol and ul list-style-type to nested %default-ol and %default-ul.

### CODE REVIEW

**Comment by tysongach** [comment]
Hi! Thanks for the PR.

1. Can you please describe in more detail what this accomplishes? What’s the goal or problem you’re trying to solve here?
2. Please review Hound’s comments and make changes accordingly. Looks to mostly be around uses tabs and not 2 spaces, which is our style.

**Comment by kristianserrano** [comment]
Hi, and thanks for responding so quickly!

Bitters, like many Sass or CSS frameworks, resets a lot of styles including unstyling and flattening ordered and unordered lists. It provides a %default-ol and %default-ul that can be employed with an extend to restyle lists for use in typical content (i.e. - discs, numbers, etc.). However, the extend only provides one list style type, disc. This pull request restores typical nested list style types via the same extend, meaning the first level of an unordered list will be disc, the second will be circle, and the third will be square. Designers can alter these if desired.

I'll update with the changes suggested by Hound shortly.

**Comment by tysongach** [comment]
@kristianserrano These changes are still using tabs instead of two spaces; can you please amend your commit?

**Comment by kylefiedler** [comment]
I think we would either want these styles inside of `%default-ul` & `%default-ol` or not at all. I've personally rarely needed these. @tysongach thoughts?

**Comment by tysongach** [comment]
@kylefiedler I’ve never needed this styling…

Thinking about it more, I don’t think this should be added:

- If I need nested lists, rather than this approach, I would probably class it out with something like a [scope](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#scope-namespaces-s-) because it’s likely user-generated content or some other kind of typographically-minded content.
- I do think the need for these styles is rare and so I think this clutters up Bitters (remember: Bitters is geared towards creating web apps/UI). This can easily be added per-project, when needed.

We appreciate the PR, though, @kristianserrano!

**Comment by kristianserrano** [comment]
I never had the impression that Bitters was intended for web apps/UI. Is this communicated somewhere and I just missed it. I think the reality is that many people want to use it and are using it for styling templates and pattern libraries, especially for things like CMS templates [because it's awesome]. Even in the case of an app, there could be content that contains a nested ul or ol, and Bitters strips the browser defaults. The existing %default-ol and %default-ul placeholders only satisfy the styles at the first level.

With respect to placing within the %default-ol and %default-ul, that was my initial approach, but it resulted in duplicated rules while trying to accommodate cases where one might have a decimal ordered list (i.e. - first-level ol) with a circle bullet list nested inside of it (i.e. - second-level ul).

While as individuals, we might rarely need these, when these nested lists do crop up, there should be some form of styling that represents the hierarchy. As I mentioned, Bitters can be and is being used for CMS templates, and content editors won't have the tools to style lists to appear as they should by default. Having something in place that will allow for these styles to be used within content elements (e.g. - article) would be helpful.

Thank you again for taking the time to consider this pull request. I think Bourbon, Neat, and Bitters are powerful tools, and I appreciate all of the careful work you've all put into it so far.

**Comment by tysongach** [comment]
@kristianserrano We mention the primary use-case of Bitters in the [second sentence](https://github.com/thoughtbot/bitters#scaffold-styles-variables-and-structure-for-bourbon-projects) of the description in our readme. We build Bitters around our personal needs here at thoughtbot.

I still think from a standpoint of base styles (mostly element/type selectors), these styles can be placed elsewhere, either in a distinct component or scope, when needed. Styling in an object-oriented way, it’s unlikely a nested list will randomly “crop up”.

Also: The best part of Bitters is that you can install it in a new project and then continually tweak it to fit _your_ needs. It’s just a starting point. And on that note, this whole thing can be forked and customized, as well.

**Comment by kristianserrano** [comment]
All fair points! I can see your perspective more clearly now, and it makes sense. Thank you for taking the time to review the pull request.

**Pull request closed without merging**
