### PR TITLE
Remove Bourbon’s prefixing

### PR DESCRIPTION
**Pull request by tysongach**
Use Autoprefixer instead.

~~(FYI: Autoprefixer does _not_ prefix `appearance`, so this mixin will stay put)~~

### CODE REVIEW

**Comment by whmii** [comment]
Noice! Shipit

**Comment by whmii** [comment]
@tysongach :bell:

**Comment by tysongach** [comment]
@whmii Autoprefixer is now about to release an update that _includes_ `appearance`, so figured I’d wait for that.

**Comment by whmii** [comment]
Cool

**Comment by jpdevries** [comment]
Are the flexbox related prefixes on the chopping block also?

**Comment by tysongach** [comment]
@jpdevries Yes. More detailed information can be found in this issue from Bourbon’s repo: https://github.com/thoughtbot/bourbon/issues/702

**Comment by tysongach** [comment]
Updated to remove the `appearance` mixin.

Awaiting release of [Autoprefixer 5.2](https://github.com/postcss/autoprefixer/releases).

**Comment by tysongach** [comment]
Merging; Autoprefixer 5.2 has been released.

**Pull request merged**
