### PR TITLE
Add middleman sub-app to make contributing easier

### PR DESCRIPTION
**Pull request by whmii**
A simple middleman site that lives in the `contrib` subdirectory. It creates an easy way for folks to contribute to bitters ;)
screen shot 2015-06-19 at 5 01 57 pm

### CODE REVIEW

**Comment by tysongach** [comment]
Will and I chatted IRL, but just to capture that here: instead of Middleman, we think just a flat HTML file and Gulp to compile the CSS would be a lighter, more-approachable solution here. This doesn’t _use_ much of Middleman, so no need for the bloat.

**Comment by whmii** [comment]
Based on a discussion with @tysongach We may look to use gulp instead of middleman.

Also, shut your face hound.

**Comment by joshuaogle** [comment]
+1 for just using Gulp for simple stuff. [There's an easy head start](https://github.com/thoughtbot/proteus-gulp) if it helps

**Comment by whmii** [comment]
Working on this today. I have a new branch I am deving out. Once I have confirmed it is successful I will be closing this PR and opening another.

**Comment by whmii** [comment]
Closing in favor of https://github.com/thoughtbot/bitters/pull/185

**Pull request closed without merging**
