### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by jferris**
* Add questions/suggestion section
* Add "About thoughtbot" section

### CODE REVIEW

**Comment by kylefiedler** [comment]
@jferris Should we remove https://github.com/thoughtbot/bitters#credits when adding this in?

**Comment by tysongach** [comment]
@jferris Can these changes (and the ones you propose for Refills and Neat) match as closely as possible to @croaky’s [changes](https://github.com/thoughtbot/bourbon/commit/83ff28fb96f1df277ca7dba232f20e3ae46fea7e) he did for Bourbon? Many people use these projects together and we made a big push last year to make them more consistent.

**Comment by tysongach** [comment]
+1 for Kyle’s comment. Also, this is adding in our old logo.

**Comment by jferris** [comment]
> +1 for Kyle’s comment. Also, this is adding in our old logo.

Is there any problem with me updating `/logo.png` to use the new logo? It seems better to do that than change the URL in every README whenever we refresh the logo.

**Comment by jferris** [comment]
@kylefiedler I removed the "Credits" section

@tysongach I updated to more closely match @croaky's changes to Bourbon.

Ready for re-review.

**Comment by jferris** [comment]
@tysongach any further comments here?

**Comment by jferris** [comment]
I opened https://github.com/thoughtbot/thoughtbot.com/pull/537 to update the logo.

**Comment by kylefiedler** [comment]
LGTM

**Pull request merged**
